image: node:22

stages:
  - verify

verify:
  stage: verify
  before_script:
    - corepack enable
  script:
    - pnpm install --frozen-lockfile
    - pnpm exec eslint "{src,apps,libs,test,prisma}/**/*.ts" --max-warnings=0
    - pnpm exec prettier --check "src/**/*.ts" "test/**/*.ts" "prisma/*.ts" "*.md" "*.json" "*.yml"
    - pnpm test
    - pnpm build
